const exhibitionConstants = {
  CHANGE_SLIDE_IDX: 'CHANGE_SLIDE_IDX',
  TOGGLE_MODAL: 'TOGGLE_MODAL',
  INIT_EXHIBITION_DETAIL_DATA: 'INIT_EXHIBITION_DETAIL_DATA',
  INIT_PICTURE_DATA: 'INIT_PICTURE_DATA'
};

export default exhibitionConstants;
