const artistConstants = {
  INIT_ARTIST_DATA: 'INIT_ARTIST_DATA',
  ADD_ARTIST_DATA: 'ADD_ARTIST_DATA',
  TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
  TOGGLE_NO_MORE_DATA: 'TOGGLE_NO_MORE_DATA'
};

export default artistConstants;
