const artistDetailConstants = {
  TOGGLE_NO_MORE_DATA: 'TOGGLE_NO_MORE_DATA',
  TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
  INIT_ARTIST_DETAIL_DATA: 'INIT_ARTIST_DETAIL_DATA',
  INIT_ARTIST_DETAIL_PICTURE_DATA: 'INIT_ARTIST_DETAIL_PICTURE_DATA',
  ADD_ARTIST_DETAIL_PICTURE_DATA: 'ADD_ARTIST_DETAIL_PICTURE_DATA'
};

export default artistDetailConstants;
