const exhibitionConstants = {
  INIT_EXHIBITION_DATA: 'INIT_EXHIBITION_DATA',
  ADD_EXHIBITION_DATA: 'ADD_EXHIBITION_DATA',
  TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
  TOGGLE_NO_MORE_DATA: 'TOGGLE_NO_MORE_DATA'
};

export default exhibitionConstants;
