const constants = {
  TOGGLE_NAVBAR: 'TOGGLE_NAVBAR',
  INIT_HOME_BANNER: 'INIT_HOME_BANNER',
  INIT_HOME_EXHIBITION: 'INIT_HOME_EXHIBITION',
  INIT_HOME_ARTIST: 'INIT_HOME_ARTIST',
  CHANGE_HOME_BANNER_IDX: 'CHANGE_HOME_BANNER_IDX',
  CHANGE_HOME_EXHIBITION_CARD_IDX: 'CHANGE_HOME_BANNER_IDX',
  CHANGE_HOME_ARTIST_CARD_IDX: 'CHANGE_HOME_BANNER_IDX'
};

export default constants;
